### PR TITLE
HBASE-22257 Remove json4s and jackson dependency from hbase spark connector

### PR DESCRIPTION
**Pull request by meszibalu**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/24/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/26/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/27/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/28/

**Comment by busbey** [comment]
scaladoc failures pulled out of the last build:

```
-1 | scaladoc | 0m 4s | spark in master failed.
-- | -- | -- | --
-1 | scaladoc | 0m 4s | root in master failed.
-1 | scaladoc | 0m 4s | hbase-connectors-assembly in master failed.
-1 | scaladoc | 0m 4s | hbase-kafka-proxy in master failed.
-1 | scaladoc | 0m 4s | hbase-spark-it in master failed.
...
+1 | scaladoc | 2m 10s | the patch passed
-- | -- | -- | --
```

yuck. I'm trying to think if this is a bug in yetus or not.

so we see that there are scala files *anywhere* in the project and so run scaladoc in every module? do we do this same thing with javadoc?

I can't tell from the yetus output what the state of hte PR was when build 28 had the patch pass. Was that where you moved the scala plugin up to top level?

I think ideally yetus would use the full plugin name so we didn't have to have it declared. so yes a yetus bug?

**Comment by busbey** [comment]
I can think of two work arounds

1) the move of the scala plugin to the top level pom, which I think you've tried once
2) update our personality to skip the scaladoc test unless we're running against exactly the module we already define the plugin on.

if this were in the main project repo I'd advocate 2, but here in the connector repo I think maybe the first is simpler at avoiding unintended side effects?

**Comment by busbey** [comment]
oh!

3. disable the built in scladoc test and write our own that properly references the plugin by full name.

this is probably the most sustainable of the options, but it's the most work

**Comment by meszibalu** [comment]
>     1. the move of the scala plugin to the top level pom, which I think you've tried once
`next try #2` was this.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/29/

**Comment by petersomogyi** [comment]
retest build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/31/

**Pull request merged**
