### PR TITLE
Dummy change in pom.xml for PR verification

### PR DESCRIPTION
**Pull request by petersomogyi**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/1/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/2/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/3/

**Comment by petersomogyi** [comment]
retest build

**Comment by petersomogyi** [comment]
retest build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/4/

**Comment by petersomogyi** [comment]
retest build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/5/

**Comment by petersomogyi** [comment]
retest build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/6/

**Comment by petersomogyi** [comment]
retest build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/7/

**Comment by petersomogyi** [comment]
retest build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/8/

**Comment by petersomogyi** [comment]
retest build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/9/

**Comment by petersomogyi** [comment]
retest build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/10/

**Comment by petersomogyi** [comment]
retest build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/11/

**Comment by petersomogyi** [comment]
retest build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/12/

**Comment by petersomogyi** [comment]
retest build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/13/

**Comment by petersomogyi** [comment]
retest build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/14/

**Comment by petersomogyi** [comment]
retest build

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/19/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/20/

**Pull request closed without merging**
