### PR TITLE
HBASE-23608 Removed redundant groupId from spark module

### PR DESCRIPTION
**Pull request by HorizonNet**

### CODE REVIEW

**Comment by HorizonNet** [comment]
retest build

**Comment by HorizonNet** [comment]
retest build

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  4s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 31s |  master passed  |
| -1 :x: |  compile  |   0m 24s |  spark in master failed.  |
| +1 :green_heart: |  javadoc  |   0m  9s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 43s |  the patch passed  |
| -1 :x: |  compile  |   0m 23s |  spark in the patch failed.  |
| -1 :x: |  javac  |   0m 23s |  spark in the patch failed.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  0s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m  8s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 24s |  spark in the patch failed.  |
|  |   |   4m 55s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Connectors-PreCommit/job/PR-61/2/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-connectors/pull/61 |
| Optional Tests | dupname javac javadoc unit xml compile |
| uname | Linux bd11f1cf2077 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | hb_maven |
| Personality | dev-support/jenkins/hbase-personality.sh |
| git revision | master / b9706c8 |
| Default Java | Oracle Corporation-1.8.0_272-b10 |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Connectors-PreCommit/job/PR-61/2/artifact/yetus-precommit-check/output/branch-compile-spark.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Connectors-PreCommit/job/PR-61/2/artifact/yetus-precommit-check/output/patch-compile-spark.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-Connectors-PreCommit/job/PR-61/2/artifact/yetus-precommit-check/output/patch-compile-spark.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Connectors-PreCommit/job/PR-61/2/artifact/yetus-precommit-check/output/patch-unit-spark.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Connectors-PreCommit/job/PR-61/2/testReport/ |
| Max. process+thread count | 42 (vs. ulimit of 12500) |
| modules | C: spark U: spark |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Connectors-PreCommit/job/PR-61/2/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  2s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 34s |  master passed  |
| -1 :x: |  compile  |   0m 24s |  spark in master failed.  |
| +1 :green_heart: |  javadoc  |   0m  9s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 45s |  the patch passed  |
| -1 :x: |  compile  |   0m 24s |  spark in the patch failed.  |
| -1 :x: |  javac  |   0m 24s |  spark in the patch failed.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m  8s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 24s |  spark in the patch failed.  |
|  |   |   4m 58s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Connectors-PreCommit/job/PR-61/3/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-connectors/pull/61 |
| Optional Tests | dupname javac javadoc unit xml compile |
| uname | Linux 83f9922375d0 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | hb_maven |
| Personality | dev-support/jenkins/hbase-personality.sh |
| git revision | master / b9706c8 |
| Default Java | Oracle Corporation-1.8.0_272-b10 |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Connectors-PreCommit/job/PR-61/3/artifact/yetus-precommit-check/output/branch-compile-spark.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Connectors-PreCommit/job/PR-61/3/artifact/yetus-precommit-check/output/patch-compile-spark.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-Connectors-PreCommit/job/PR-61/3/artifact/yetus-precommit-check/output/patch-compile-spark.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Connectors-PreCommit/job/PR-61/3/artifact/yetus-precommit-check/output/patch-unit-spark.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Connectors-PreCommit/job/PR-61/3/testReport/ |
| Max. process+thread count | 42 (vs. ulimit of 12500) |
| modules | C: spark U: spark |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Connectors-PreCommit/job/PR-61/3/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 22s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 38s |  master passed  |
| +1 :green_heart: |  compile  |   0m 54s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 54s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 52s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 53s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 53s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  0s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 51s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   7m 21s |  spark in the patch passed.  |
|  |   |  15m 45s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Connectors-PreCommit/job/PR-61/4/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-connectors/pull/61 |
| Optional Tests | dupname javac javadoc unit xml compile |
| uname | Linux dcaf0802ec52 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | hb_maven |
| Personality | dev-support/jenkins/hbase-personality.sh |
| git revision | master / 21e9d2b |
| Default Java | Oracle Corporation-1.8.0_275-b01 |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Connectors-PreCommit/job/PR-61/4/testReport/ |
| Max. process+thread count | 922 (vs. ulimit of 12500) |
| modules | C: spark U: spark |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Connectors-PreCommit/job/PR-61/4/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
