### PR TITLE
HBASE-22613: Bump Apache Avro to 1.9.0

### PR DESCRIPTION
**Pull request by Fokko**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/48/

**Comment by meszibalu** [comment]
retest build

**Comment by meszibalu** [comment]
retest build

**Comment by HorizonNet** [comment]
Depends on https://github.com/apache/hbase/pull/326. Closed due to comment on related PR. Feel free to reopen after we have a consensus.

**Pull request closed without merging**
