### PR TITLE
HBASE-21432 Add Apache Yetus integration for hbase-connectors repository

### PR DESCRIPTION
**Pull request by petersomogyi**
Add Dockerfile for Yetus patchprocess with Maven 3.6

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/16/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/PreCommit-HBASE-CONNECTORS-Build/17/

**Comment by petersomogyi** [comment]
The currently used Docker image have Apache Maven 3.3.9 but we require minimum 3.5.0. This validations still use 3.3.9 since this patch adds the new Dockerfile so the parent commit does not have it.

**Comment by petersomogyi** [comment]
I copied the Dockerfile from hbase's dev-support/docker/Dockerfile for Yetus. The problem with yetus' image is that it uses Maven 3.3.9 but this repository requires 3.5.0 at least. I believe we don't need any additional packages on this image, I removed ruby and C specific packages.

Apparently there is a conflict between the used surefire and JDK. I'm still looking into what would be the best way to solve this.
https://stackoverflow.com/questions/53010200/maven-surefire-could-not-find-forkedbooter-class

**Pull request merged**
