### PR TITLE
HBASE-28054 Add spotless in hbase-connectors pre commit check

### PR DESCRIPTION
**Pull request by NihalJain**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://ci-hbase.apache.org/job/HBase-Connectors-PreCommit/job/PR-122/1/console in case of problems.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 23s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 18s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  spotless  |   0m 15s |  branch has no errors when running spotless:check.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  2s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  spotless  |   0m 11s |  patch has no errors when running spotless:check.  |
||| _ Other Tests _ |
|  |   |   1m 17s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-Connectors-PreCommit/job/PR-122/1/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-connectors/pull/122 |
| Optional Tests | dupname spotless shellcheck shelldocs |
| uname | Linux 06924e36afd5 5.4.0-156-generic #173-Ubuntu SMP Tue Jul 11 07:25:22 UTC 2023 x86_64 GNU/Linux |
| Build tool | hb_maven |
| Personality | dev-support/jenkins/hbase-personality.sh |
| git revision | master / ee2b51c |
| Max. process+thread count | 34 (vs. ulimit of 12500) |
| modules | C:  U:  |
| Console output | https://ci-hbase.apache.org/job/HBase-Connectors-PreCommit/job/PR-122/1/console |
| versions | git=2.20.1 shellcheck=0.5.0 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by NihalJain** [comment]
Hi @Apache9, @Reidddddd Could you please review?

**Comment by NihalJain** [comment]
Rasied https://github.com/apache/hbase-connectors/pull/123 to demo failure

**Review by Apache9 — APPROVED** [review]

**Review by Reidddddd — APPROVED** [review]

**Pull request merged**
